#ifndef SQFLAB_UI_MAINMENU_CONTROLS_HPP
#define SQFLAB_UI_MAINMENU_CONTROLS_HPP

#define SQFLAB_MM_IDD 86540

#define SQFLAB_MM_IDC_BTN_LIGHTSOURCES 86541
#define SQFLAB_MM_IDC_BTN_MARKERS 86542
#define SQFLAB_MM_IDC_BTN_PARTICLES 86543

#endif
